site_name: Nimbus e-resources
theme:
  logo: assets/logo.png
  palette:
    primary: orange
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.sections

nav:
  - Home: index.md
  - Resources:
    - Articles:
      - Cloud Computing: resources/articles/cloud-computing.md
    - guides:
      - guides: resources/guides/guide.md
    - videos: 
      - videos: resources/videos/videos.md
    - MUN: 
      - An overview of CBRN: resources/MUN/cbrn-article.md
  - About: 
    - Nimbus: about/Nimbus.md
    - Announcements: about/announcements.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: Copyright &copy; 2025 Priyongshu Paul
