site_name: Nimbus e-resources
theme:
  logo: assets/logo.png
  palette:
    primary: orange
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.sections

# Configure static file serving
use_directory_urls: true

nav:
  - Home: index.md
  - Resources:
    - Articles:
      - Principles of Natural Justice: resources/articles/principles-of-natural-justice.md
      - Dummy's guide to economic logic: resources/articles/economic-logic.md
      - Thinking from the lens of nations: resources/articles/nation.md
    - Guides:
      - Asian Parliamentary Debating: resources/guides/guide.md
    - Videos: 
      - videos: resources/videos/videos.md
    - MUN: 
      - An overview of CBRN: resources/MUN/cbrn-article.md
  - About: 
    - Nimbus: about/Nimbus.md
    - Announcements: about/announcements.md
  - Sponsors: sponsors/sponsors.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: Copyright &copy; 2025 Priyongshu Paul
